SET NAMES 'latin1';
DROP DATABASE IF EXISTS baseDatos;
CREATE DATABASE IF NOT EXISTS baseDatos DEFAULT CHARACTER SET utf8;
USE baseDatos;

CREATE TABLE usuarios(
    id_usr      INTEGER NOT NULL AUTO_INCREMENT,
    nombre      VARCHAR(20) NOT NULL,
    correo      VARCHAR(40) NOT NULL,

PRIMARY KEY(id_usr)
)DEFAULT CHARACTER SET utf8;